server:
  port: 8082
zuul:
  routes:
    dynamic:
      path: /beacon/**
      # see GatekeeperProxyDecider for where the target is calculated
      url: http://route-created-by-rules/

gatekeeper:
  beaconServer:
    url: http://fake-mssng-beacon.staging.dnastack.com/

logging:
  level:
    com.dnastack: DEBUG
