spring:
  cloud:
    gateway:
      routes:
        - predicates:
            - Path=${gatekeeper.beaconServer.predicate}
          filters:
            - name: Gatekeeper
              args:
                strip-prefix: ${gatekeeper.beaconServer.strip-prefix}
                public-prefix: ${gatekeeper.beaconServer.public-prefix}
                registered-prefix: ${gatekeeper.beaconServer.registered-prefix}
                controlled-prefix: ${gatekeeper.beaconServer.controlled-prefix}
            - PrependUriPath=${gatekeeper.beaconServer.url}
            - StripAuthHeader
            - name: AddBasicAuthHeader
              args:
                username: ${outbound.basic.username}
                password: ${outbound.basic.password}
            - PreserveHostHeader
            - Logging
          uri: ${gatekeeper.beaconServer.url}
        - predicates:
            - Path=${gatekeeper.metadataServer.predicate}
          filters:
            - name: Gatekeeper
              args:
                strip-prefix: 1
                public-prefix: ${gatekeeper.metadataServer.public-prefix}
                registered-prefix: ${gatekeeper.metadataServer.registered-prefix}
                controlled-prefix: ${gatekeeper.metadataServer.controlled-prefix}
                authChallengeHandler: LoginRedirect
            - PrependUriPath=${gatekeeper.metadataServer.url}
            - StripAuthHeader
            - name: AddBasicAuthHeader
              args:
                username: ${outbound.basic.username}
                password: ${outbound.basic.password}
            - Logging
          uri: ${gatekeeper.metadataServer.url}